### ISSUE TITLE
Installation fails without IsoSpecPy installed on mac os x 10.14.3

### ISSUE THREAD

**Issue by PMSeitzer** [mciach/masserstein#1]
Followed installation instructions, during `setup.py`, there is a problem installing dependency `IsoSpecPy`:

```
Running IsoSpecPy-2.0.1/setup.py -q bdist_egg --dist-dir /var/folders/kt/pkd6vlkx51n88jjls5j6l87r0000gp/T/easy_install-56ffs0at/IsoSpecPy-2.0.1/egg-dist-tmp-p3m01oo0
warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from IsoSpec++/unity-build.cpp:27:
IsoSpec++/allocator.cpp:18:10: fatal error: 'iostream' file not found
#include <iostream>
         ^~~~~~~~~~
1 warning and 1 error generated.
error: Setup script exited with error: command 'gcc' failed with exit status 1
```

I was able to get around this problem by retrieving the source for the IsoSpec dependency from [here](https://pypi.org/simple/isospecpy/)

and in `IsoSpecPy-2.0.1/setup.py`, adding the suggested command line option `stdlib=c++`:
```
cmodule = Extension('IsoSpecCppPy',
                    sources = ['IsoSpec++/unity-build.cpp'],
                    extra_compile_args = '-stdlib=libc++ -mtune=native -march=native -O3 -std=c++17'.split() #+ ['-DDEBUG']
                    )
```
after that, just run `make` in `IsoSpecPy-2.0.1`, which will put this dependency on the `easy-install.pth`.

re-running the `wassersteinms/setup.py` script works for me now

**Comment by michalsta** [comment]
Hi, (IsoSpec maintainer here)

We can't really just add the "-stdlib=libc++" as it breaks the build on all other platforms (GCC doesn't accept that as a valid parameter). That seems to be needed for clang/OSX, but on macosx the "gcc" command is often actually clang masquerading as GCC, but sometimes not, and we'll probably have to add some convoluted logic to detect that...

**Comment by PMSeitzer** [comment]
@michalsta, Could you use `platform.system()` to conditionally include or exclude the `stdlib=libc++` flag in `extra_compile_args`?

**Comment by michalsta** [comment]
Nah, not that easy, that'd break the build on OSXes where g++ really is g++ and not clang pretending to be g++. Regardless, I think I've managed to work some (rather ugly...) workaround for this, would you mind running ```pip install IsoSpecPy==2.0.2b2``` and seeing if it works now?

**Comment by PMSeitzer** [comment]
Hey @michalsta, `pip install IsoSpecPy==2.0.2b2` is working for me.
