### ISSUE TITLE
IndexError raised in python 3.7

### ISSUE THREAD

**Issue by PMSeitzer** [mciach/masserstein#2]
In `generate_test_data.py`, there is an illegal matrix axis:
```
wM = np.zeros((k,k))
for i in range(k):
    for j in range(k):
            wM[i,j] = spectra[i].WSDistance(spectra[j])
```
In python version 3.7, this raises a `StopIteration` exception.  workaround is to guard like this:

```
wM = np.zeros((k,k))
for i in range(k):
    for j in range(k):
        try:
            wM[i,j] = spectra[i].WSDistance(spectra[j])
        except: StopIteration
```
See  [this thread](https://stackoverflow.com/questions/51700960/runtimeerror-generator-raised-stopiteration-every-time-i-try-to-run-app)

**Comment by PMSeitzer** [comment]
Also in `WSDeconv.py`:
```
        try:
            ii = 0
            leftoverprob = other.confs[0][1]
            for mass, prob in self.confs:
                while leftoverprob <= prob:
                    yield (other.confs[ii][0], mass, leftoverprob)
                    prob -= leftoverprob
                    ii += 1
                    leftoverprob = other.confs[ii][1]
                yield (other.confs[ii][0], mass, prob)
                leftoverprob -= prob
        except: IndexError or StopIteration
```

**Comment by mciach** [comment]
I've changed the generator stopping criterion to the Python 3.7 standard, everything should be working now without the additional try-except clauses.

**Comment by michalsta** [comment]
Note: this is the wrong syntax for catching exceptions in Python. This will catch any exception not just IndexError or StopIteration, then compute the or of the types and ignore the results. Should be:

```
try:
    ...
except (IndexError, StopIteration):
    pass
```

**Comment by PMSeitzer** [comment]
Great, thank you!
